### ISSUE TITLE
Auto-start

### ISSUE THREAD

**Issue by Jordinho** [CodeSingh/rpi-led-scoreboard#1]
How can I change the code to keep the program from auto-starting?

**Comment by CodeSingh** [comment]
If you want to stop showing the scores then you can go to the webpage to set the scoreboard display to 'OFF'.

Another way to stop the display from starting up is to edit the crontab file and comment out the lines that start the program.

Thanks

**Comment by Jordinho** [comment]
Thanks, that worked for me.  I enjoyed the project!  Thank you.
