### ISSUE TITLE
How To Install EPL Scoreboard

### ISSUE THREAD

**Issue by jeepdrvr71** [CodeSingh/rpi-led-scoreboard#2]
Do you have any instructions on how to install this project? Also does it work with the Pi Zero 2?

**Comment by jeepdrvr71** [comment]
http://www.codesingh.com/2020/07/how-to-build-live-raspberry-pi-led.html

For anyone wanting instructions

**Comment by CodeSingh** [comment]
Unfortunately, I haven't been able to test it on Pi Zero 2 yet. 

The instructions are for the original version. There have been some improvements over time but the instructions should still be valid.
